package pojo;
// Generated May 17, 2020 5:48:09 PM by Hibernate Tools 4.3.1



/**
 * AnalyticReview generated by hbm2java
 */
public class AnalyticReview  implements java.io.Serializable {


     private int reviewId;
     private String month;
     private String review;

    public AnalyticReview() {
    }

	
    public AnalyticReview(int reviewId) {
        this.reviewId = reviewId;
    }
    public AnalyticReview(int reviewId, String month, String review) {
       this.reviewId = reviewId;
       this.month = month;
       this.review = review;
    }
   
    public int getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(int reviewId) {
        this.reviewId = reviewId;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    public String getReview() {
        return this.review;
    }
    
    public void setReview(String review) {
        this.review = review;
    }




}


