package pojo;
// Generated May 17, 2020 5:48:09 PM by Hibernate Tools 4.3.1



/**
 * Customerpark generated by hbm2java
 */
public class Customerpark  implements java.io.Serializable {


     private Integer parkId;
     private int slotId;
     private int cid;
     private String time;
     private String date;
     private String type;
     private String duration;

    public Customerpark() {
    }

    public Customerpark(int slotId, int cid, String time, String date, String type, String duration) {
       this.slotId = slotId;
       this.cid = cid;
       this.time = time;
       this.date = date;
       this.type = type;
       this.duration = duration;
    }
   
    public Integer getParkId() {
        return this.parkId;
    }
    
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }
    public int getSlotId() {
        return this.slotId;
    }
    
    public void setSlotId(int slotId) {
        this.slotId = slotId;
    }
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }




}


