package pojo;
// Generated May 17, 2020 5:48:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Income generated by hbm2java
 */
public class Income  implements java.io.Serializable {


     private Date incomeDate;
     private Float totIncome;

    public Income() {
    }

	
    public Income(Date incomeDate) {
        this.incomeDate = incomeDate;
    }
    public Income(Date incomeDate, Float totIncome) {
       this.incomeDate = incomeDate;
       this.totIncome = totIncome;
    }
   
    public Date getIncomeDate() {
        return this.incomeDate;
    }
    
    public void setIncomeDate(Date incomeDate) {
        this.incomeDate = incomeDate;
    }
    public Float getTotIncome() {
        return this.totIncome;
    }
    
    public void setTotIncome(Float totIncome) {
        this.totIncome = totIncome;
    }




}


