package pojo;
// Generated May 17, 2020 5:48:09 PM by Hibernate Tools 4.3.1



/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private int cid;
     private String date;
     private String time;
     private String status;

    public Order() {
    }

	
    public Order(int cid, String date, String time) {
        this.cid = cid;
        this.date = date;
        this.time = time;
    }
    public Order(int cid, String date, String time, String status) {
       this.cid = cid;
       this.date = date;
       this.time = time;
       this.status = status;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


