package pojo;
// Generated May 17, 2020 5:48:09 PM by Hibernate Tools 4.3.1



/**
 * Parkslot generated by hbm2java
 */
public class Parkslot  implements java.io.Serializable {


     private Integer slotId;
     private String available;
     private String slotname;

    public Parkslot() {
    }

    public Parkslot(String available, String slotname) {
       this.available = available;
       this.slotname = slotname;
    }
   
    public Integer getSlotId() {
        return this.slotId;
    }
    
    public void setSlotId(Integer slotId) {
        this.slotId = slotId;
    }
    public String getAvailable() {
        return this.available;
    }
    
    public void setAvailable(String available) {
        this.available = available;
    }
    public String getSlotname() {
        return this.slotname;
    }
    
    public void setSlotname(String slotname) {
        this.slotname = slotname;
    }




}


