package pojo;
// Generated May 17, 2020 5:48:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReserveTable generated by hbm2java
 */
public class ReserveTable  implements java.io.Serializable {


     private Integer tableResId;
     private Date reserveDate;
     private String time;
     private int tableCount;
     private String reservedTables;

    public ReserveTable() {
    }

    public ReserveTable(Date reserveDate, String time, int tableCount, String reservedTables) {
       this.reserveDate = reserveDate;
       this.time = time;
       this.tableCount = tableCount;
       this.reservedTables = reservedTables;
    }
   
    public Integer getTableResId() {
        return this.tableResId;
    }
    
    public void setTableResId(Integer tableResId) {
        this.tableResId = tableResId;
    }
    public Date getReserveDate() {
        return this.reserveDate;
    }
    
    public void setReserveDate(Date reserveDate) {
        this.reserveDate = reserveDate;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public int getTableCount() {
        return this.tableCount;
    }
    
    public void setTableCount(int tableCount) {
        this.tableCount = tableCount;
    }
    public String getReservedTables() {
        return this.reservedTables;
    }
    
    public void setReservedTables(String reservedTables) {
        this.reservedTables = reservedTables;
    }




}


