package pojo;
// Generated May 17, 2020 5:48:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rooms generated by hbm2java
 */
public class Rooms  implements java.io.Serializable {


     private Integer roomId;
     private int roomNumber;
     private String roomType;
     private int adults;
     private int children;
     private int duration;
     private double advance;
     private Date checkIn;
     private Date checkOut;

    public Rooms() {
    }

    public Rooms(int roomNumber, String roomType, int adults, int children, int duration, double advance, Date checkIn, Date checkOut) {
       this.roomNumber = roomNumber;
       this.roomType = roomType;
       this.adults = adults;
       this.children = children;
       this.duration = duration;
       this.advance = advance;
       this.checkIn = checkIn;
       this.checkOut = checkOut;
    }
   
    public Integer getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }
    public int getRoomNumber() {
        return this.roomNumber;
    }
    
    public void setRoomNumber(int roomNumber) {
        this.roomNumber = roomNumber;
    }
    public String getRoomType() {
        return this.roomType;
    }
    
    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }
    public int getAdults() {
        return this.adults;
    }
    
    public void setAdults(int adults) {
        this.adults = adults;
    }
    public int getChildren() {
        return this.children;
    }
    
    public void setChildren(int children) {
        this.children = children;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public double getAdvance() {
        return this.advance;
    }
    
    public void setAdvance(double advance) {
        this.advance = advance;
    }
    public Date getCheckIn() {
        return this.checkIn;
    }
    
    public void setCheckIn(Date checkIn) {
        this.checkIn = checkIn;
    }
    public Date getCheckOut() {
        return this.checkOut;
    }
    
    public void setCheckOut(Date checkOut) {
        this.checkOut = checkOut;
    }




}


