package pojo;
// Generated May 17, 2020 5:48:09 PM by Hibernate Tools 4.3.1



/**
 * Sndmessagetosupplier generated by hbm2java
 */
public class Sndmessagetosupplier  implements java.io.Serializable {


     private Integer idmessage;
     private String suppliername;
     private String suppliermessage;
     private String senddate;
     private String sendtime;

    public Sndmessagetosupplier() {
    }

    public Sndmessagetosupplier(String suppliername, String suppliermessage, String senddate, String sendtime) {
       this.suppliername = suppliername;
       this.suppliermessage = suppliermessage;
       this.senddate = senddate;
       this.sendtime = sendtime;
    }
   
    public Integer getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(Integer idmessage) {
        this.idmessage = idmessage;
    }
    public String getSuppliername() {
        return this.suppliername;
    }
    
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername;
    }
    public String getSuppliermessage() {
        return this.suppliermessage;
    }
    
    public void setSuppliermessage(String suppliermessage) {
        this.suppliermessage = suppliermessage;
    }
    public String getSenddate() {
        return this.senddate;
    }
    
    public void setSenddate(String senddate) {
        this.senddate = senddate;
    }
    public String getSendtime() {
        return this.sendtime;
    }
    
    public void setSendtime(String sendtime) {
        this.sendtime = sendtime;
    }




}


